name: bf tests 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        BFSOURCE: m68kd.bf gengen.bf src/hello.b src/div10.b src/atoi.b

    steps:
      - uses: actions/checkout@v3
      - name: Install lha
        run: sudo apt-get install -y lhasa
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install amitools
      - name: Get bfc and original source examples
        run: |
          wget http://main.aminet.net/dev/lang/brainfuck-2.lha
          lha -x brainfuck-2.lha
      - name: Compile m68k executables
        run: |
          for BF in $BFSOURCE; do vamos bfc < $BF > ${BF}.exe; done
      - name: Test that executables decompile back to expected source
        run: |
          for BF in $BFSOURCE; do
            printf "\n=====\n\n$BF:\n  "
            diff -s <(vamos m68kd.bf.exe < ${BF}.exe | sed 's/+-]/]/g') <(cat $BF | tr -dc "+<>[],.-")
          done
      - name: Test that the invalid magic cookies are recognised as such:
        run: |
          vamos gengen.bf.exe < data/bad_cookie_03F4.bin | grep "ERROR: Input != text|Amiga EXE"
          vamos gengen.bf.exe < data/bad_cookie_04F3.bin | grep "ERROR: Input != text|Amiga EXE"
      - name: Test that an Amiga OS executable does not error and is converted. Also bfc gen exe = 65532 lines.
        run: |
          vamos gengen.bf.exe < gengen.bf.exe | grep -v "ERROR: Input != text|Amiga EXE"
          test $(vamos gengen.bf.exe < gengen.bf.exe | wc -l) = 65532
