name: bf tests 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        BFSOURCE: m68kd.bf src/hello.b src/div10.b src/atoi.b

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lhasa
          version: 0.3
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install amitools
      - name: Get bfc and original source examples
        run: |
          wget http://main.aminet.net/dev/lang/brainfuck-2.lha
          lha -x brainfuck-2.lha
      - name: Compile m68k executables
        run: |
          for BF in $BFSOURCE; do vamos bfc < $BF > ${BF}.exe; done
      - name: Test that executables compile back to expected source
        run: |
          for BF in $BFSOURCE; do
            printf "\n=====\n\n$BF:\n  "
            diff -s <(vamos m68kd.bf.exe < ${BF}.exe | sed 's/+-]/]/g') <(cat $BF | tr -dc "+<>[],.-")
          done
